// This file is automatically generated by Firebase Studio.
// Do not edit manually.

// To change which Firebase project your app is connected to,
// update the project ID in the --project flag of the `studio:start` command.

import { FirebaseApp, FirebaseOptions, initializeApp, getApp, getApps } from "firebase/app";

const firebaseConfig: FirebaseOptions = {
  apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
  measurementId: process.env.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID || undefined,
};

function initializeFirebase(): FirebaseApp | null {
  // Defensively check for essential Firebase config variables.
  if (!firebaseConfig.apiKey || !firebaseConfig.projectId) {
    if (typeof window !== 'undefined') {
      console.warn(
        `[Firebase] Core configuration is missing from environment variables. Firebase services will be disabled.`
      );
    }
    return null;
  }
  
  if (getApps().length > 0) {
    return getApp();
  }
  
  return initializeApp(firebaseConfig);
}

export const firebaseApp = initializeFirebase();
